- hosts: myweb
  tasks:
  - debug:
      msg: "Running playbook"

  - name: "Installing httpd"
    package:
        name:
            - wget
            - httpd
            - php
            - net-tools
        state: present

  - name: "Copying index page"
    copy:
       src: "/home/rizwan/ansible-code/index.php"
       dest: "/var/www/html/index.php"

  - name: "Restarting service"
    service:
        name: httpd
        state: restarted
        enabled: true


  - name: "copying var files"
    template:
        dest: "/home/khan/"
        src: "/home/rizwan/ansible-code/my.txt"

- hosts: mylb
  tasks:
  - name: "Copying custom config file for haProxy"
    copy:
      src: "haproxy.cfg"
      dest: "/etc/haproxy/haproxy.cfg"

  - name: "Installing HA-proxy"
    package:
       name:
           - haproxy
       state: present

  - name: "Restarting haProxy"
    service:
       name: haproxy
       state: restarted
       enabled: true
       
